services:
    ci:
        working_dir: /website
        volumes:
            - ..:/website
            - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
        build:
            context: .
            args:
                HUGO_VERSION: "0.145.0"
        environment:
            - VAULT_ADDR
            - VAULT_TOKEN
