version: "3"
services:
    ci:
        working_dir: /workdir
        volumes:
            - ..:/workdir
        build:
            context: .
            args:
                HUGO_VERSION: "0.104.3"
