services:
    ci:
        working_dir: /workdir
        volumes:
            - ..:/workdir
        build:
            context: .
            args:
                HUGO_VERSION: "0.145.0"
        environment:
            - VAULT_ADDR
            - VAULT_TOKEN
