# prettier-ignore
steps:
  - label: ':shipit: Build and deploy site changes'
    if: 'build.branch == "main"'
    key: deploy
    agents:
      queue: nicholas.cloud
    command: .buildkite/build.sh

  - label: ':mag: Scan for newsletters'
    if: 'build.branch == "main" && build.source != "schedule"'
    depends_on: deploy
    agents:
      queue: nicholas.cloud
    command: .buildkite/trigger-newsletter-if-new-issue.sh

  - label: ":cloudflare: Purge Cloudflare cache"
    if: 'build.branch == "main"'
    depends_on: deploy
    agents:
      queue: nicholas.cloud
    command: .buildkite/purge-cloudflare-cache.sh
