# prettier-ignore
steps:
  - label: ':hugo: Build website and run checks'
    key: build
    command: .buildkite/build.sh
    artifact_paths:
      - website.tar.gz
    plugins:
      - docker-compose#v5.6.0:
          run: ci
          config: .buildkite/docker-compose.yml

  - label: ':cloudflare: Sync to R2'
    if: 'build.branch == "main"'
    key: sync-to-r2
    depends_on: build
    command: .buildkite/sync-to-r2.sh
    concurrency_group: $BUILDKITE_PIPELINE_SLUG/deploy
    concurrency: 1

  - label: ':shipit: Deploy website'
    skip: "Currently serving website from Cloudflare Workers"
    if: 'build.branch == "main"'
    key: deploy
    depends_on: build
    command: .buildkite/deploy.sh
    concurrency_group: $BUILDKITE_PIPELINE_SLUG/deploy
    concurrency: 1
    plugins:
      - docker-compose#v5.6.0:
          run: ci
          config: .buildkite/docker-compose.yml
          mount-buildkite-agent: true

  - label: ":cloudflare: Purge Cloudflare cache"
    if: 'build.branch == "main"'
    key: purge-cloudflare-cache
    depends_on: sync-to-r2
    command: .buildkite/purge-cloudflare-cache.sh
