# prettier-ignore
steps:
  - label: ':shipit: Build website and run checks'
    key: build
    command: .buildkite/build.sh
    plugins:
      - docker#3.13.0:
          image: "registry.gitlab.com/pages/hugo:0.101.0"

  # TODO: Deploy step

  - label: ':mag: Scan for newsletters'
    if: 'build.branch == "main" && build.source != "schedule"'
    depends_on: deploy
    agents:
      website: nicholas.cloud
    command: .buildkite/trigger-newsletter-if-new-issue.sh

  - label: ":cloudflare: Purge Cloudflare cache"
    if: 'build.branch == "main"'
    depends_on: deploy
    agents:
      website: nicholas.cloud
    command: .buildkite/purge-cloudflare-cache.sh
