# prettier-ignore
steps:
  - label: ':hugo: Build website and run checks'
    key: build
    command: .buildkite/build.sh
    artifact_paths:
      - "website.tar.gz"
    plugins:
      - docker-compose#v3.10.0:
          run: ci
          config: .buildkite/docker-compose.yml

  - label: ':shipit: Deploy website'
    if: 'build.branch == "main"'
    key: deploy
    depends_on: build
    agents:
      queue: nicholas.cloud
    command: .buildkite/deploy.sh

  - label: ':mag: Scan for newsletters'
    if: 'build.branch == "main" && build.source != "schedule"'
    depends_on: deploy
    agents:
      queue: nicholas.cloud
    command: .buildkite/trigger-newsletter-if-new-issue.sh

  - label: ":cloudflare: Purge Cloudflare cache"
    if: 'build.branch == "main"'
    depends_on: deploy
    agents:
      queue: nicholas.cloud
    command: .buildkite/purge-cloudflare-cache.sh
