# prettier-ignore
steps:
  - label: ':shipit: Build website and run checks'
    key: build
    command: .buildkite/build.sh
    artifact_paths:
      - "public/**/*"
    plugins:
      - docker-compose#v3.10.0:
          run: ci

  # TODO: Deploy step

  - label: ':mag: Scan for newsletters'
    if: 'build.branch == "main" && build.source != "schedule"'
    depends_on: deploy
    agents:
      website: nicholas.cloud
    command: .buildkite/trigger-newsletter-if-new-issue.sh

  - label: ":cloudflare: Purge Cloudflare cache"
    if: 'build.branch == "main"'
    depends_on: deploy
    agents:
      website: nicholas.cloud
    command: .buildkite/purge-cloudflare-cache.sh
