version: "3.3"
services:
    plausible_db:
        image: postgres:12
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres

    plausible_events_db:
        image: yandex/clickhouse-server:21.3.2.5
        volumes:
            - event-data:/var/lib/clickhouse
            - ./clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
            - ./clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
        ulimits:
            nofile:
                soft: 262144
                hard: 262144

    plausible:
        image: plausible/analytics:v{{ plausible_version }}
        command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
        depends_on:
            - plausible_db
            - plausible_events_db
        ports:
            - 8000:8000
        env_file:
            - plausible-conf.env

volumes:
    db-data:
        driver: local
    event-data:
        driver: local
