- name: Allow SSH egress
  become: true
  community.general.ufw:
      rule: allow
      port: https
      direction: in
- name: Install Nginx
  become: true
  ansible.builtin.apt:
      name:
          - nginx
      state: latest
- name: Configure Nginx
  register: configure_nginx
  become: true
  ansible.builtin.copy:
      src: ../files/{{ nginx_hostname }}.nginx
      dest: /etc/nginx/sites-enabled/{{ nginx_hostname }}

- name: Create certificate directory
  become: true
  ansible.builtin.file:
      path: /etc/nginx/certs
      state: directory

- name: Sync TLS certificates
  register: set_nginx_certificates
  become: true
  no_log: true
  ansible.builtin.copy:
      content: "{{ item.content }}"
      dest: "{{ item.dest }}"
      mode: "0600"
  with_items:
      - content: "{{ lookup('community.general.passwordstore', 'website/' + nginx_hostname + '.cert returnall=true') }}"
        dest: /etc/nginx/certs/{{ nginx_hostname }}.cert
      - content: "{{ lookup('community.general.passwordstore', 'website/' + nginx_hostname + '.key returnall=true') }}"
        dest: /etc/nginx/certs/{{ nginx_hostname }}.key

# TODO: Add a rescue option to restore a backup of Nginx config/certs
- name: Validate Nginx configuration
  when: configure_nginx.changed or set_nginx_certificates.changed
  become: true
  ansible.builtin.shell: nginx -t

- name: Restart Nginx
  when: configure_nginx.changed or set_nginx_certificates.changed
  become: true
  ansible.builtin.systemd:
      name: nginx
      state: restarted
