- name: Ensure website directory exists
  register: ensure_website_directory
  become: true
  ansible.builtin.file:
      path: /var/www/nicholas.cloud
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

- name: Sync public files
  ansible.posix.synchronize:
      src: ~/Google Drive/nicholas.cloud/public-files/
      dest: /var/www/nicholas.cloud/files/
      delete: true

- name: Trigger build of website on Buildkite
  when: ensure_website_directory.changed
  vars:
      buildkite_api_token: "{{ lookup('community.general.passwordstore', 'website/buildkite-api-token') }}"
  ansible.builtin.uri:
      url: https://api.buildkite.com/v2/organizations/nchlswhttkr/pipelines/website/builds
      method: POST
      headers:
          Authorization: Bearer {{ buildkite_api_token }}
      body_format: json
      body:
          commit: HEAD
          branch: main
      status_code: [201]

- name: Wait for website build in Buildkite to finish
  when: ensure_website_directory.changed
  register: buildkite_result
  vars:
      buildkite_api_token: "{{ lookup('community.general.passwordstore', 'website/buildkite-api-token') }}"
  ansible.builtin.uri:
      url: https://api.buildkite.com/v2/organizations/nchlswhttkr/pipelines/website/builds?branch=main&per_page=1
      headers:
          Authorization: Bearer {{ buildkite_api_token }}
      body_format: json
  until: buildkite_result.json[0].state in ["passed", "blocked", "failed"]
  failed_when: buildkite_result.json[0].state == "failed"
  retries: 5
  delay: 15
