---
- name: Restore a backup
  hosts: web # TODO: Change to analytics group after setting up a dedicated host
  gather_facts: false
  vars:
      ansible_become_password: "{{ lookup('community.general.passwordstore', 'website/host-passwords/' + inventory_hostname) }}"
  tasks:
      - name: Query date of most recent backup
        register: get_date
        ansible.builtin.shell: find /mnt/backups/analytics/ -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1 | cut -d '/' -f 5
      - name: Set backup date and destination to restore from
        ansible.builtin.set_fact:
            date: "{{ get_date.stdout }}"
            backup_destination: "/mnt/backups/analytics/{{ get_date.stdout }}"
      - name: Request confirmation before continuing
        register: confirm
        ansible.builtin.pause:
            prompt: Type "RESTORE" to restore backup from {{ date }}
        failed_when: confirm.user_input != "RESTORE" # TODO: Type date of restore to confirm
      - name: Stop Plausible
        ansible.builtin.shell: systemctl --user stop plausible
      - name: Prune Docker containers
        ansible.builtin.shell: docker container prune --force
      - name: Delete existing Plausible volumes
        ansible.builtin.shell: docker volume rm plausible-hosting_db-data plausible-hosting_event-data
      - name: Restore Plausible user data from backup file
        ansible.builtin.shell: docker run --rm --mount "source=plausible-hosting_db-data,destination=/var/lib/postgresql/data" --mount "type=bind,source={{ backup_destination }},destination=/backup,readonly" ubuntu tar --extract --file /backup/plausible-user-data.tar.gz --directory /var/lib/postgresql/data/
      - name: Restore Plausible event data from backup file
        ansible.builtin.shell: docker run --rm --mount "source=plausible-hosting_event-data,destination=/var/lib/clickhouse" --mount "type=bind,source={{ backup_destination }},destination=/backup,readonly" ubuntu tar --extract --file /backup/plausible-event-data.tar.gz --directory /var/lib/clickhouse/
      - name: Restart Plausible
        ansible.builtin.shell: systemctl --user start plausible
