---
- name: Create a backup
  hosts: all
  gather_facts: false
  remote_user: nicholas
  tasks:
      - name: Ensure user-owned backup root directory exists
        become: true
        ansible.builtin.file:
            path: /mnt/backups/nicholas
            owner: nicholas
            group: nicholas
            state: directory
      - name: Set backup destination
        ansible.builtin.set_fact:
            backup_destination: /mnt/backups/nicholas/{{ date }}
      - name: Ensure backup path exists
        ansible.builtin.file:
            path: "{{ backup_destination }}"
            state: directory
      - name: Stop Plausible
        ansible.builtin.shell: systemctl --user stop plausible
      - name: Create backup file of Plausible user data
        ansible.builtin.shell: docker run --rm --mount "source=plausible-hosting_db-data,destination=/var/lib/postgresql/data,readonly" --mount "type=bind,source={{ backup_destination }},destination=/backup" ubuntu tar --gzip --create --file /backup/plausible-user-data.tar.gz --directory /var/lib/postgresql/data/ .
      - name: Create backup file of Plausible event data
        ansible.builtin.shell: docker run --rm --mount "source=plausible-hosting_event-data,destination=/var/lib/clickhouse,readonly" --mount "type=bind,source={{ backup_destination }},destination=/backup" ubuntu tar --gzip --create --file /backup/plausible-event-data.tar.gz --directory /var/lib/clickhouse/ .
      - name: Restart Plausible
        ansible.builtin.shell: systemctl --user start plausible
      - name: Stop Writefreely
        ansible.builtin.shell: systemctl --user stop writefreely
      - name: Create backup file of Writefreely data and keys
        ansible.builtin.shell: tar --gzip --create --file "{{ backup_destination }}/writefreely-data.tar.gz" --directory ~/writefreely/ writefreely.db keys/
        args:
            warn: false # ansible.builtin.unarchive doesn't play nice with absolute paths
      - name: Restart Writefreely
        ansible.builtin.shell: systemctl --user start writefreely
