- name: Set up DDNS
  hosts: all
  remote_user: nicholas
  tasks:
      - name: Install dependencies
        become: true
        ansible.builtin.apt:
            name: musl
            state: latest
      - name: Install DDNS
        when: ansible_local.ddns.ddns_version|d != ddns_version
        ansible.builtin.shell: |
            set -euo pipefail
            curl --silent --fail --location https://github.com/hugomd/cloudflare-ddns/releases/download/{{ ddns_version }}/cloudflare-ddns_{{ ddns_version }}_linux_amd64.tar.gz \
                | tar -zx -C ~/ "cloudflare-ddns"
            sudo mv ~/cloudflare-ddns /usr/local/bin/ddns
            jq --null-input '.ddns_version = "{{ ddns_version }}"' | sudo tee /etc/ansible/facts.d/ddns.fact
        args:
            executable: /bin/bash
      - name: Configure DDNS
        vars:
            cloudflare_zone_id: "{{ lookup('community.general.passwordstore', 'website/cloudflare-zone-id') }}"
            cloudflare_api_token: "{{ lookup('community.general.passwordstore', 'website/cloudflare-api-token') }}"
        register: configure_ddns
        no_log: true
        ansible.builtin.template:
            src: ../ddns.j2.cfg
            dest: /home/nicholas/ddns.cfg
            mode: "0600"
      - name: Run DDNS
        when: configure_ddns.changed
        ansible.builtin.shell: ddns -config /home/nicholas/ddns.cfg
