- name: Set up Nginx
  hosts: all
  remote_user: nicholas
  gather_facts: false
  tasks:
      - name: Install Nginx and dependencies
        become: true
        ansible.builtin.apt:
            name:
                - nginx
                - fcgiwrap # required for git-http-backend
            state: latest
      - name: Configure Nginx
        register: configure_nginx
        become: true
        ansible.builtin.copy:
            src: ../nicholas.cloud.nginx
            dest: /etc/nginx/sites-enabled/nicholas.cloud
            # can't validate here, do it later
      - name: Sync TLS certificates
        register: set_nginx_certificates
        no_log: true
        ansible.builtin.copy:
            content: "{{ item.content }}"
            dest: "{{ item.dest }}"
            mode: "0600"
        with_items:
            - content: "{{ lookup('community.general.passwordstore', 'website/nicholas.cloud.certificate returnall=true') }}"
              dest: /home/nicholas/nicholas.cloud.certificate
            - content: "{{ lookup('community.general.passwordstore', 'website/nicholas.cloud.key returnall=true') }}"
              dest: /home/nicholas/nicholas.cloud.key
      - name: Restart Nginx
        when: configure_nginx.changed or set_nginx_certificates.changed
        ansible.builtin.shell: |
            set -euo pipefail
            sudo nginx -t
            sudo systemctl restart nginx
        args:
            executable: /bin/bash
