- name: Set up Plausible
  hosts: all
  remote_user: nicholas
  tasks:
      - name: Install Docker
        register: install_docker
        when: ansible_local.docker.docker_version_release|d != docker_version_release or ansible_local.docker.containerd_version_release|d != containerd_version_release or ansible_local.docker.docker_compose_version|d != docker_compose_version
        ansible.builtin.shell: |
            set -euo pipefail
            curl --fail --silent \
                https://download.docker.com/linux/ubuntu/dists/{{ docker_ubuntu_release}}/pool/stable/amd64/containerd.io_{{ containerd_version_release }}_amd64.deb \
                > /tmp/containerd.deb
            curl --fail --silent \
                https://download.docker.com/linux/ubuntu/dists/{{ docker_ubuntu_release}}/pool/stable/amd64/docker-ce-cli_{{ docker_version_release }}_amd64.deb \
                > /tmp/docker-cli.deb
            curl --fail --silent \
                https://download.docker.com/linux/ubuntu/dists/{{ docker_ubuntu_release}}/pool/stable/amd64/docker-ce_{{ docker_version_release }}_amd64.deb \
                > /tmp/docker.deb
            sudo dpkg -i /tmp/containerd.deb
            sudo dpkg -i /tmp/docker-cli.deb
            sudo dpkg -i /tmp/docker.deb
            sudo usermod -aG docker nicholas
            sudo curl -L "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            jq --null-input '
              .docker_version_release = "{{ docker_version_release }}" |
              .containerd_version_release = "{{ containerd_version_release }}" |
              .docker_compose_version = "{{ docker_compose_version }}"
            ' | sudo tee /etc/ansible/facts.d/docker.fact
        args:
            executable: /bin/bash
      - name: Ensure Plausible directory exists
        ansible.builtin.file:
            path: /home/nicholas/plausible-hosting
            state: directory
      - name: Configure Plausible
        register: configure_plausible
        no_log: true
        vars:
            plausible_admin_password: "{{ lookup('community.general.passwordstore', 'website/plausible-admin-password') }}"
            plausible_secret_key: "{{ lookup('community.general.passwordstore', 'website/plausible-secret-key') }}"
            mailgun_relay_password: "{{ lookup('community.general.passwordstore', 'website/mailgun-relay-password') }}"
        ansible.builtin.template:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            mode: "{{ item.mode }}"
        with_items:
            - src: ../plausible/plausible-conf.j2.env
              dest: /home/nicholas/plausible-hosting/plausible-conf.env
              mode: "0600"
            - src: ../plausible/plausible-smtp-conf.j2.env
              dest: /home/nicholas/plausible-hosting/plausible-smtp-conf.env
              mode: "0600"
            - src: ../plausible/docker-compose.j2.yml
              dest: /home/nicholas/plausible-hosting/docker-compose.yml
              mode: "0644"
            - src: ../plausible/clickhouse-config.xml
              dest: /home/nicholas/plausible-hosting/
              mode: "0644"
            - src: ../plausible/clickhouse-user-config.xml
              dest: /home/nicholas/plausible-hosting/
              mode: "0644"
            - src: ../plausible/plausible.service
              dest: /home/nicholas/.config/systemd/user/
              mode: "0644"
      - name: Restart Plausible
        when: install_docker.changed or configure_plausible.changed
        ansible.builtin.shell: |
            set -euo pipefail
            systemctl --user stop plausible
            systemctl --user daemon-reload
            (cd plausible-hosting && sudo docker-compose pull)
            systemctl --user start plausible
            systemctl --user enable plausible
        args:
            executable: /bin/bash
