# TODO type date of restore rather than RESTORE
---
- name: Restore a backup
  hosts: all
  gather_facts: false
  remote_user: nicholas
  tasks:
      - name: Query date of most recent backup
        register: get_date
        ansible.builtin.shell: find /mnt/backups/nicholas/ -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1 | cut -d '/' -f 5
      - name: Set backup date and destination to restore from
        ansible.builtin.set_fact:
            date: "{{ get_date.stdout }}"
            backup_destination: "/mnt/backups/nicholas/{{ get_date.stdout }}"
      - name: Request confirmation before continuing
        register: confirm
        ansible.builtin.pause:
            prompt: Type "RESTORE" to restore backup from {{ date }}
        failed_when: confirm.user_input != "RESTORE"
      - name: Stop Plausible
        ansible.builtin.shell: systemctl --user stop plausible
      - name: Delete existing Plausible volumes
        ansible.builtin.shell: docker volume rm --force plausible-hosting_db-data plausible-hosting_event-data
      - name: Restore Plausible user data from backup file
        ansible.builtin.shell: docker run --rm --mount "source=plausible-hosting_db-data,destination=/var/lib/postgresql/data" --mount "type=bind,source={{ backup_destination }},destination=/backup,readonly" ubuntu tar -xf /backup/plausible-user-data.tar.gz /var/lib/postgresql/data
      - name: Create backup file of Plausible event data
        ansible.builtin.shell: docker run --rm --mount "source=plausible-hosting_event-data,destination=/var/lib/clickhouse" --mount "type=bind,source={{ backup_destination }},destination=/backup,readonly" ubuntu tar -xf /backup/plausible-event-data.tar.gz /var/lib/clickhouse
      - name: Restart Plausible
        ansible.builtin.shell: systemctl --user start plausible
      - name: Stop Writefreely
        ansible.builtin.shell: systemctl --user stop writefreely
      - name: Overwrite Writefreely data
        ansible.builtin.shell: tar --overwrite -xf "{{ backup_destination }}/writefreely-data.tar.gz"
        args:
            warn: false # ansible.builtin.unarchive doesn't play nice with absolute paths
      - name: Restart Writefreely
        ansible.builtin.shell: systemctl --user start writefreely
