buildkite_version: "3.32.1"
buildkite_organization_slug: nchlswhttkr
buildkite_pipeline_slug: website

ddns_version: "2.1.0"

hugo_version: "0.87.0"

docker_ubuntu_release: "focal"
docker_version_release: "20.10.7~3-0~ubuntu-focal"
containerd_version_release: "1.4.6-1"
docker_compose_version: "1.29.2"
plausible_version: "1.3.0"

mandarin_duck_version: "1.2"

writefreely_version: "0.13.1"
