- name: Ensure Plausible directory exists
  ansible.builtin.file:
      path: /home/{{ ansible_user }}/plausible-hosting
      state: directory
- name: Configure Plausible
  register: configure_plausible
  no_log: true
  vars:
      plausible_admin_password: "{{ lookup('community.general.passwordstore', 'website/plausible-admin-password') }}"
      plausible_secret_key: "{{ lookup('community.general.passwordstore', 'website/plausible-secret-key') }}"
      mailgun_relay_password: "{{ lookup('community.general.passwordstore', 'website/mailgun-relay-password') }}"
  ansible.builtin.template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
  with_items:
      - src: ../templates/plausible-conf.j2.env
        dest: /home/{{ ansible_user }}/plausible-hosting/plausible-conf.env
        mode: "0600"
      - src: ../templates/docker-compose.j2.yml
        dest: /home/{{ ansible_user }}/plausible-hosting/docker-compose.yml
        mode: "0644"
      - src: ../files/clickhouse-config.xml
        dest: /home/{{ ansible_user }}/plausible-hosting/
        mode: "0644"
      - src: ../files/clickhouse-user-config.xml
        dest: /home/{{ ansible_user }}/plausible-hosting/
        mode: "0644"
      - src: ../files/plausible.service
        dest: /home/{{ ansible_user }}/.config/systemd/user/
        mode: "0644"
- name: Ensure Docker images are up to date
  when: configure_plausible.changed
  ansible.builtin.shell: docker-compose pull
  args:
      chdir: /home/{{ ansible_user }}/plausible-hosting
- name: Restart Plausible
  when: configure_plausible.changed
  ansible.builtin.systemd:
      name: plausible
      scope: user
      state: restarted
      daemon_reload: true
